#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BibliotecaUdeA.Droid.Resource", IsApplication=true)]

namespace BibliotecaUdeA.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dark_blue = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int dark_gray = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int gray = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int light_blue = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int light_gray = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int light_more_blue = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int light_yellow = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int red = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int white = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int white_bone = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int yellow = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int myButton = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
